### ISSUE TITLE
Gem Load Error is: undefined method `has?' for Sass::Util:Module

### ISSUE THREAD

**Issue by neonmate** [makandra/katapult#16]
I see following error when saying `katapult new $APPLICATION_NAME`:

```
run  rake db:drop:all db:create:all parallel:create from "."
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'compass-rails'.
Gem Load Error is: undefined method `has?' for Sass::Util:Module
Did you mean?  hash
Backtrace for gem load error is:
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:5:in `has?'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:9:in `included'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/sass-3.5.2/lib/sass/script/functions.rb:632:in `include'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/sass-3.5.2/lib/sass/script/functions.rb:632:in `include'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions.rb:16:in `<module:Functions>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions.rb:13:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass/sass_extensions.rb:8:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass.rb:4:in `each'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/compass-rails-2.0.0/lib/compass-rails.rb:1:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/Users/neonmate/Projects/$APPLICATION_NAME/config/application.rb:17:in `<top (required)>'
/Users/neonmate/Projects/$APPLICATION_NAME/Rakefile:4:in `require_relative'
/Users/neonmate/Projects/$APPLICATION_NAMEoin/Rakefile:4:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:688:in `raw_load_rakefile'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:97:in `block in load_rakefile'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:96:in `load_rakefile'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:80:in `block in run'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/Users/neonmate/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/bin/rake:22:in `load'
/Users/neonmate/.rvm/gems/ruby-2.4.1/bin/rake:22:in `<main>'
/Users/neonmate/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/neonmate/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonmate** [comment]
Hard to tell what the problem was, here is my Gemfile.lock, where the problem does not exists anymore. I will close this issue:

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.4)
      actionpack (= 5.1.4)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.4)
      actionview (= 5.1.4)
      activesupport (= 5.1.4)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.4)
      activesupport (= 5.1.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_type (0.7.4)
      activerecord (>= 3.2)
    activejob (5.1.4)
      activesupport (= 5.1.4)
      globalid (>= 0.3.6)
    activemodel (5.1.4)
      activesupport (= 5.1.4)
    activerecord (5.1.4)
      activemodel (= 5.1.4)
      activesupport (= 5.1.4)
      arel (~> 8.0)
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    airbrussh (1.3.0)
      sshkit (>= 1.6.1, != 1.7.0)
    arel (8.0.0)
    assignable_values (0.13.1)
      activerecord (>= 2.3)
    better_errors (2.4.0)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    bindex (0.5.0)
    binding_of_caller (0.7.3)
      debug_inspector (>= 0.0.1)
    builder (3.2.3)
    byebug (9.1.0)
    capistrano (3.10.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.3.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-maintenance (1.2.0)
      capistrano (>= 3.0)
    capistrano-rails (1.3.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capybara (2.15.4)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.18)
      capybara (>= 1.0, < 3)
      launchy
    childprocess (0.8.0)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    coderay (1.1.2)
    concurrent-ruby (1.0.5)
    crass (1.0.2)
    cucumber (2.1.0)
      builder (>= 2.1.2)
      cucumber-core (~> 1.3.0)
      diff-lcs (>= 1.1.3)
      gherkin3 (~> 3.1.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.3.1)
      gherkin3 (~> 3.1.0)
    cucumber-rails (1.5.0)
      capybara (>= 1.1.2, < 3)
      cucumber (>= 1.3.8, < 4)
      mime-types (>= 1.17, < 4)
      nokogiri (~> 1.5)
      railties (>= 4, < 5.2)
    cucumber_factory (1.11.8)
      activerecord
      activesupport
      cucumber
      cucumber_priority (>= 0.2.0)
    cucumber_priority (0.2.0)
      cucumber
    daemons (1.2.5)
    database_cleaner (1.6.2)
    debug_inspector (0.0.3)
    diff-lcs (1.3)
    edge_rider (0.3.2)
      activerecord
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubi (1.7.0)
    erubis (2.7.0)
    eventmachine (1.2.5)
    exception_notification (4.2.2)
      actionmailer (>= 4.0, < 6)
      activesupport (>= 4.0, < 6)
    factory_girl (4.9.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.9.0)
      factory_girl (~> 4.9.0)
      railties (>= 3.0.0)
    ffi (1.9.18)
    formatador (0.2.5)
    gherkin3 (3.1.2)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    guard (2.14.1)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    haml (5.0.4)
      temple (>= 0.8.0)
      tilt
    haml-rails (1.0.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 6.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    has_defaults (0.4.4)
      activerecord
    html2haml (2.2.0)
      erubis (~> 2.7.0)
      haml (>= 4.0, < 6)
      nokogiri (>= 1.6.0)
      ruby_parser (~> 3.5)
    http_parser.rb (0.6.0)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    katapult (0.3.0)
      rails (= 5.1.4)
      spring
      webpacker
    launchy (2.4.3)
      addressable (~> 2.3)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.1.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.12)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_mime (0.1.4)
    mini_portile2 (2.3.0)
    minitest (5.10.3)
    modularity (2.0.1)
    multi_json (1.12.2)
    multi_test (0.1.2)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.2.0)
    nio4r (2.1.0)
    nokogiri (1.8.1)
      mini_portile2 (~> 2.3.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    parallel (1.12.0)
    parallel_tests (2.17.0)
      parallel
    pg (0.21.0)
    pry (0.11.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    public_suffix (3.0.0)
    query_diet (0.6.2)
    rack (2.0.3)
    rack-livereload (0.3.16)
      rack
    rack-proxy (0.6.2)
      rack
    rack-test (0.7.0)
      rack (>= 1.0, < 3)
    rails (5.1.4)
      actioncable (= 5.1.4)
      actionmailer (= 5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      activemodel (= 5.1.4)
      activerecord (= 5.1.4)
      activesupport (= 5.1.4)
      bundler (>= 1.3.0)
      railties (= 5.1.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.1.4)
      actionpack (= 5.1.4)
      activesupport (= 5.1.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.2.1)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.0)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)
    ruby_dep (1.5.0)
    ruby_parser (3.10.1)
      sexp_processor (~> 4.9)
    rubyzip (1.2.1)
    selenium-webdriver (3.7.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    sexp_processor (4.10.0)
    shellany (0.0.1)
    shoulda-matchers (3.1.2)
      activesupport (>= 4.0.0)
    spreewald (1.10.0)
      cucumber
      cucumber_priority
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-cucumber (1.0.1)
      spring (>= 0.9.1)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.15.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    temple (0.8.0)
    thin (1.7.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    timecop (0.9.1)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webpacker (3.0.2)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    whenever (0.9.7)
      chronic (>= 0.6.3)
    will_paginate (3.1.6)
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_type
  assignable_values
  better_errors
  binding_of_caller
  byebug
  capistrano-bundler
  capistrano-maintenance
  capistrano-rails
  capybara
  capybara-screenshot
  cucumber (< 2.2)
  cucumber-rails
  cucumber_factory
  database_cleaner
  edge_rider
  exception_notification
  factory_girl_rails
  guard-livereload
  haml-rails
  has_defaults
  katapult
  launchy
  listen (< 3.2)
  modularity
  parallel_tests
  pg
  query_diet
  rack-livereload
  rails
  rspec
  rspec-rails
  selenium-webdriver
  shoulda-matchers
  spreewald
  spring
  spring-commands-cucumber
  spring-commands-rspec
  thin
  timecop
  web-console
  webpacker
  whenever
  will_paginate

BUNDLED WITH
   1.15.4
```
