### ISSUE TITLE
Create wui without crud

### ISSUE THREAD

**Issue by judithroth** [makandra/katapult#7]
application_model.rb:

```
model 'MyModel' do |my_model|
  ...
end

wui 'MyModel', model: 'MyModel' do |wui|
  wui.action :create
  wui.action :index
  wui.action :show
end
```

fails with:

```
~/.rvm/gems/ruby-2.3.0/gems/katapult-0.2.0/lib/katapult/wui.rb:58:in `path': Unknown action 'edit' (Katapult::WUI::UnknownActionError)
    from (erb):19:in `template'
    from ~/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
    from ~/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
    from ~/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
    from ~/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
```

**Comment by codener** [comment]
Thanks for reporting this, it is a true shortcoming of Katapult. It's on the roadmap.

**Comment by codener** [comment]
Closing because we've abandoned Katapult.
